-- ════════════════════════════════════════════════════════════════════════════
-- Showbiz Elite Show Choir — Disneyland & Universal Studios (Jun 14-20, 2026)
-- Tour Host: Linda Deming (efbf888c-5348-4071-b720-961e2795698c)
-- Run this in the Supabase SQL Editor.
--
-- All IDs use gen_random_uuid() (the column default). A DO block captures the
-- generated tour/day IDs so agenda rows can reference their parents.
-- Re-runnable: deletes the tour by name first; FK cascade clears its days,
-- items, and post_trip record.
-- ════════════════════════════════════════════════════════════════════════════

DO $$
DECLARE
  v_tour uuid;
  d1 uuid; d2 uuid; d3 uuid; d4 uuid; d5 uuid; d6 uuid; d7 uuid;
BEGIN

  -- ─── Safety: remove prior copy (cascade clears days/items/post_trip) ────────
  DELETE FROM tours WHERE name = 'Showbiz Elite Show Choir - Disneyland & Universal Studios';

  -- ─── Tour ───────────────────────────────────────────────────────────────────
  INSERT INTO tours (
    tour_host_id, name, school, contact_name, contact_email,
    destination, dates, start_date, end_date,
    status, transport_type, bus_capacity, student_count, notes, access_codes
  ) VALUES (
    'efbf888c-5348-4071-b720-961e2795698c',
    'Showbiz Elite Show Choir - Disneyland & Universal Studios',
    'Showbiz Elite Show Choir',
    'Taneil Serr',
    'taneilserr@gmail.com',
    'Anaheim, CA',
    'Jun 14-20, 2026',
    '2026-06-14',
    '2026-06-20',
    'committed',
    'bus',
    56,
    26,
    'Holiday Motor Coach LLC, 56 passenger. Hotel: Anaheim Suites Hotel, 101 E Katella Ave, Anaheim CA 92802 (3 Bunk Suites, 8 Double Queen Rooms, 2 Double Queen with Sofa). 40 total participants: 26 performing students, 13 chaperones, 1 tour host.',
    '{"coordinator":"SHOWBIZ26","teacher":"TEACH26","driver":"DRIVE26","student":"STAR26"}'
  ) RETURNING id INTO v_tour;

  -- ─── Agenda Days ──────────────────────────────────────────────────────────────
  INSERT INTO agenda_days (tour_id, day_number, date, sort_order) VALUES (v_tour, 1, 'Jun 14, 2026', 1) RETURNING id INTO d1;
  INSERT INTO agenda_days (tour_id, day_number, date, sort_order) VALUES (v_tour, 2, 'Jun 15, 2026', 2) RETURNING id INTO d2;
  INSERT INTO agenda_days (tour_id, day_number, date, sort_order) VALUES (v_tour, 3, 'Jun 16, 2026', 3) RETURNING id INTO d3;
  INSERT INTO agenda_days (tour_id, day_number, date, sort_order) VALUES (v_tour, 4, 'Jun 17, 2026', 4) RETURNING id INTO d4;
  INSERT INTO agenda_days (tour_id, day_number, date, sort_order) VALUES (v_tour, 5, 'Jun 18, 2026', 5) RETURNING id INTO d5;
  INSERT INTO agenda_days (tour_id, day_number, date, sort_order) VALUES (v_tour, 6, 'Jun 19, 2026', 6) RETURNING id INTO d6;
  INSERT INTO agenda_days (tour_id, day_number, date, sort_order) VALUES (v_tour, 7, 'Jun 20, 2026', 7) RETURNING id INTO d7;

  -- ─── Day 1 — Jun 14 (Sunday): Travel Idaho Falls → Anaheim ────────────────────
  INSERT INTO agenda_items (day_id, tour_id, sort_order, time, type, title, detail, public_note, address, travel_method, contact_name, driver_note, internal_note, meal_pay_type, stipend_amount) VALUES
  (d1, v_tour, 1,  '5:00 AM',  'meeting', 'Meet at Church',                            NULL,                                                          'Eat breakfast before you come or bring food with you. No dairy on the bus.',                                       '5366 1st St, Idaho Falls, ID 83401', NULL,  NULL, NULL, NULL,                                                              NULL,      NULL),
  (d1, v_tour, 2,  '5:20 AM',  'travel',  'Depart for Flying J Travel Center',          'About 2 hours 40 minutes',                                    NULL,                                                                                                               '1172 W 21st St, Ogden, UT 84401',    'bus', NULL, 'Head south on I-15', NULL,                                              NULL,      NULL),
  (d1, v_tour, 3,  '8:00 AM',  'free',    'Arrive at Flying J - Bathroom Break',        NULL,                                                          '15 minute stop. Back on bus by 8:15 AM.',                                                                          '1172 W 21st St, Ogden, UT 84401',    NULL,  NULL, NULL, NULL,                                                              NULL,      NULL),
  (d1, v_tour, 4,  '8:15 AM',  'travel',  'Depart for Fillmore, Utah',                  'About 2 hours 40 minutes',                                    NULL,                                                                                                               '1060 So. Highway 99, Fillmore, UT 84631', 'bus', NULL, NULL, NULL,                                                          NULL,      NULL),
  (d1, v_tour, 5,  '11:00 AM', 'food',    'Lunch Stop - Fillmore, Utah',                NULL,                                                          '50 minute lunch stop. Options: Costa Vida, Krispy Krunchy Chicken, Port of Subs.',                                 '1060 So. Highway 99, Fillmore, UT 84631', NULL, NULL, NULL, NULL,                                                          'stipend', 15),
  (d1, v_tour, 6,  '11:50 AM', 'travel',  'Depart for St. George, Utah',                'About 2 hours 15 minutes',                                    NULL,                                                                                                               '2841 S 60 E, St. George, UT 84790',  'bus', NULL, NULL, NULL,                                                          NULL,      NULL),
  (d1, v_tour, 7,  '2:00 PM',  'free',    'Arrive St. George - Driver Change & Break',  NULL,                                                          '20 minute bathroom break.',                                                                                        '2841 S 60 E, St. George, UT 84790',  NULL,  NULL, NULL, 'Boost Driver change. Savannah Hill meets group here.',          NULL,      NULL),
  (d1, v_tour, 8,  '2:20 PM',  'travel',  'Depart for Barstow, CA',                     'About 4 to 4.5 hours. Time change entering Nevada — gain one hour (2:30 PM becomes 1:30 PM).', NULL,                                                                              '2821 Lenwood Rd, Barstow, CA 92311', 'bus', NULL, NULL, NULL,                                                          NULL,      NULL),
  (d1, v_tour, 9,  '5:45 PM',  'food',    'Dinner Stop - Barstow, CA',                  NULL,                                                          '60 minute dinner stop. Options: In-N-Out Burger, Panda Express, Jersey Mike''s Subs, Carl''s Jr.',                 '2821 Lenwood Rd, Barstow, CA 92311', NULL,  NULL, NULL, NULL,                                                              'stipend', 15),
  (d1, v_tour, 10, '6:45 PM',  'travel',  'Depart for Anaheim',                         'About 2 hours 15 minutes.',                                   NULL,                                                                                                               '101 E Katella Ave, Anaheim, CA 92802','bus', NULL, 'Hotel is at 101 E Katella Ave. Put traffic cones out when leaving to keep bus spot.', NULL, NULL, NULL),
  (d1, v_tour, 11, '9:00 PM',  'hotel',   'Check In - Anaheim Suites Hotel',            NULL,                                                          'Lights out 10:00 PM.',                                                                                             '101 E Katella Ave, Anaheim, CA 92802',NULL, NULL, NULL, 'Bus driver needs to put traffic cones out when leaving to ensure spot stays available.', NULL, NULL);

  -- ─── Day 2 — Jun 15 (Monday): Disneyland Workshop ─────────────────────────────
  INSERT INTO agenda_items (day_id, tour_id, sort_order, time, type, title, detail, public_note, address, travel_method, contact_name, driver_note, internal_note, meal_pay_type, stipend_amount) VALUES
  (d2, v_tour, 1,  '6:00 AM',  'free',     'Wake Up',                                   NULL, NULL,                                                                                                                                                            NULL,                                       NULL, NULL, NULL, NULL, NULL, NULL),
  (d2, v_tour, 2,  '6:30 AM',  'food',     'Breakfast - Hotel',                         NULL, 'Please wear wristband to breakfast.',                                                                                                                            '101 E Katella Ave, Anaheim, CA 92802',      NULL, NULL, NULL, NULL, 'group', NULL),
  (d2, v_tour, 3,  '6:50 AM',  'activity', 'Walk to Toy Story Parking',                 NULL, 'Meet in lobby and walk together to Toy Story.',                                                                                                                  NULL,                                       NULL, NULL, NULL, NULL, NULL, NULL),
  (d2, v_tour, 4,  '7:05 AM',  'activity', 'Arrive at Toy Story - Disney Entry',        NULL, 'Go through security and take shuttle into Disney.',                                                                                                               'Toy Story Parking, Anaheim, CA',           NULL, NULL, NULL, NULL, NULL, NULL),
  (d2, v_tour, 5,  '7:30 AM',  'activity', 'Scan Ticket - Disneyland',                  NULL, 'Chaperones help purchase Lightning Lane passes. Park Hopper to Disneyland available at 11:00 AM. $40 Disney Dining Card provided plus $10 on Till. Parade times: 1:30 PM and 2:45 PM (from It''s a Small World to Main Street).', 'Disneyland Resort, Anaheim, CA', NULL, NULL, NULL, '$40 Disney Dining Card provided separately.', 'stipend', 10),
  (d2, v_tour, 6,  '9:40 AM',  'activity', 'Walk to Workshop Location',                 NULL, 'Follow the walking link to Stage 12 Food Truck area.',                                                                                                           NULL,                                       NULL, NULL, NULL, 'Photography and videography not permitted backstage. No stocking feet, bare feet, sandals or flip flops. No food or drink except bottled water with cap. Limited space for adult chaperones.', NULL, NULL),
  (d2, v_tour, 7,  '10:00 AM', 'activity', 'Meet Guest Talent Coordinator',             NULL, 'Meet at Stage 12 Food Truck.',                                                                                                                                   'Stage 12, Disneyland Resort, Anaheim, CA', NULL, NULL, NULL, NULL, NULL, NULL),
  (d2, v_tour, 8,  '10:30 AM', 'activity', 'Disney Workshop',                           NULL, 'Workshop runs until 12:00 PM. No photography or videography permitted backstage. Closed toe shoes required. No food except bottled water.',                          'Disneyland Resort, Anaheim, CA',           NULL, NULL, NULL, NULL, NULL, NULL),
  (d2, v_tour, 9,  '9:30 PM',  'activity', 'Fireworks & Castle Show - Wondrous Journeys',NULL, 'Wondrous Journeys fireworks show.',                                                                                                                              'Disneyland, Anaheim, CA',                  NULL, NULL, NULL, NULL, NULL, NULL),
  (d2, v_tour, 10, '10:00 PM', 'meeting',  'Meet at Main Entrance Esplanade',           NULL, 'Located between Disneyland and California Adventure. Take shuttle back to Toy Story at 10:15 PM.',                                                                'Main Entrance Esplanade, Disneyland Resort, Anaheim, CA', NULL, NULL, NULL, NULL, NULL, NULL),
  (d2, v_tour, 11, '11:00 PM', 'hotel',    'Arrive at Hotel',                           NULL, 'Lights out 11:15 PM.',                                                                                                                                           '101 E Katella Ave, Anaheim, CA 92802',      NULL, NULL, NULL, NULL, NULL, NULL);

  -- ─── Day 3 — Jun 16 (Tuesday): Long Beach Clinic, Hollywood, Medieval Times ────
  INSERT INTO agenda_items (day_id, tour_id, sort_order, time, type, title, detail, public_note, address, travel_method, contact_name, driver_note, internal_note, meal_pay_type, stipend_amount) VALUES
  (d3, v_tour, 1,  '7:00 AM',  'free',     'Wake Up & Get Ready',                       NULL, NULL,                                                                                                                                  NULL,                                                              NULL, NULL, NULL, NULL, NULL, NULL),
  (d3, v_tour, 2,  '7:30 AM',  'food',     'Breakfast - Hotel',                         NULL, 'Please wear wristband to breakfast.',                                                                                                 '101 E Katella Ave, Anaheim, CA 92802',                            NULL, NULL, NULL, NULL, 'group', NULL),
  (d3, v_tour, 3,  '8:10 AM',  'travel',   'Depart for Cal State Long Beach',           'About 30-35 minutes.', NULL,                                                                                                                'Carpenter Performing Arts Center, 6200 E Atherton St, Long Beach, CA 90840', 'bus', NULL, NULL, NULL, NULL, NULL),
  (d3, v_tour, 4,  '9:00 AM',  'activity', 'Clinic with Professor Bruce Rogers',        NULL, 'Professor Rogers will be in UMC A 301.',                                                                                              'Carpenter Performing Arts Center, 6200 E Atherton St, Long Beach, CA 90840', NULL, 'Professor Bruce Rogers', NULL, NULL, NULL, NULL),
  (d3, v_tour, 5,  '10:15 AM', 'travel',   'Depart for Hard Rock Cafe Hollywood',       'About 1 hour.', NULL,                                                                                                                       '6801 Hollywood Blvd Suite 105, Los Angeles, CA',                  'bus', NULL, NULL, NULL, NULL, NULL),
  (d3, v_tour, 6,  '11:15 AM', 'activity', 'Hollywood - Walk of Fame & Shopping',       NULL, 'Shopping, Hollywood Walk of Fame, view Hollywood Sign from Ovation Mall Level 3. TCL Chinese Theatre and Dolby Theatre (where the Oscars are held).', 'Hollywood Blvd, Los Angeles, CA',                  NULL, NULL, NULL, NULL, NULL, NULL),
  (d3, v_tour, 7,  '12:15 PM', 'food',     'Lunch at Hard Rock Cafe',                   NULL, NULL,                                                                                                                                  '6801 Hollywood Blvd Suite 105, Los Angeles, CA',                  NULL, NULL, NULL, 'Send Tiffany Orgill $30 for lunch. Order BBQ sandwich for Braelynn Earmes and pay in store.', 'group', NULL),
  (d3, v_tour, 8,  '1:30 PM',  'travel',   'Depart for Santa Monica Pier',              'About 45-60 minutes.', NULL,                                                                                                                '200 Santa Monica Pier, Santa Monica, CA',                         'bus', NULL, 'Best parking is Lot 4S at 2030 Ocean Ave. Rate is $48/bus, paid at gate.', NULL, NULL, NULL),
  (d3, v_tour, 9,  '2:30 PM',  'activity', 'Santa Monica Pier - Free Time',             NULL, 'Free time at Santa Monica Pier until 4:15 PM.',                                                                                       '200 Santa Monica Pier, Santa Monica, CA',                         NULL, NULL, NULL, NULL, NULL, NULL),
  (d3, v_tour, 10, '4:15 PM',  'travel',   'Depart for Medieval Times',                 '1.5 to 2.5 hours.', NULL,                                                                                                                   '7662 Beach Blvd, Buena Park, CA',                                 'bus', NULL, NULL, NULL, NULL, NULL),
  (d3, v_tour, 11, '7:00 PM',  'activity', 'Medieval Times Dinner & Tournament',        NULL, 'Dinner and show included.',                                                                                                           '7662 Beach Blvd, Buena Park, CA',                                 NULL, NULL, NULL, 'Bus driver invited to dinner and show.', 'group', NULL),
  (d3, v_tour, 12, '9:00 PM',  'hotel',    'Return to Hotel',                           NULL, 'Lights out 10:00 PM.',                                                                                                                '101 E Katella Ave, Anaheim, CA',                                  'bus', NULL, NULL, NULL, NULL, NULL);

  -- ─── Day 4 — Jun 17 (Wednesday): Disney California Adventure Performance ───────
  INSERT INTO agenda_items (day_id, tour_id, sort_order, time, type, title, detail, public_note, address, travel_method, contact_name, driver_note, internal_note, meal_pay_type, stipend_amount) VALUES
  (d4, v_tour, 1,  '6:00 AM',  'free',     'Wake Up & Get Ready',                       NULL, NULL,                                                                                                                                                                  NULL,                                       NULL, NULL, NULL, NULL, NULL, NULL),
  (d4, v_tour, 2,  '6:30 AM',  'food',     'Breakfast - Hotel',                         NULL, 'Please wear wristband to breakfast.',                                                                                                                                  '101 E Katella Ave, Anaheim, CA 92802',     NULL, NULL, NULL, NULL, 'group', NULL),
  (d4, v_tour, 3,  '6:50 AM',  'activity', 'Walk to Toy Story Parking',                 NULL, 'Meet in lobby and walk together.',                                                                                                                                     NULL,                                       NULL, NULL, NULL, NULL, NULL, NULL),
  (d4, v_tour, 4,  '7:05 AM',  'activity', 'Arrive at Toy Story - Disney Entry',        NULL, 'Go through security and take shuttle into Disney.',                                                                                                                    'Toy Story Parking, Anaheim, CA',           NULL, NULL, NULL, NULL, NULL, NULL),
  (d4, v_tour, 5,  '7:30 AM',  'activity', 'Scan Ticket - Disney California Adventure', NULL, 'Chaperones help purchase Lightning Lane passes. Park Hopper to Disneyland available at 11:00 AM. $40 Disney Dining Card provided plus $10 on Till. Parade times: 1:30 PM and 2:45 PM.', NULL,                          NULL, NULL, NULL, NULL, 'stipend', 10),
  (d4, v_tour, 6,  '10:10 AM', 'activity', 'Walk to Performance Location',              NULL, 'Follow the walking link to performance location.',                                                                                                                     NULL,                                       NULL, NULL, NULL, NULL, NULL, NULL),
  (d4, v_tour, 7,  '10:30 AM', 'activity', 'Meet Guest Talent Coordinator',             NULL, 'Meet at Stage 12 Food Truck.',                                                                                                                                         'Stage 12, Disney California Adventure, Anaheim, CA', NULL, NULL, NULL, NULL, NULL, NULL),
  (d4, v_tour, 8,  '12:00 PM', 'activity', 'Disney Performance',                        NULL, 'Group performance at Disney. Get in Virtual Queue on Disneyland App for World of Color night show — optional but provides better viewing.',                          'Disney California Adventure, Anaheim, CA', NULL, NULL, NULL, NULL, NULL, NULL),
  (d4, v_tour, 9,  '9:00 PM',  'activity', 'World of Color - DCA',                      NULL, 'World of Color show at Disney California Adventure.',                                                                                                                  'Disney California Adventure, Anaheim, CA', NULL, NULL, NULL, NULL, NULL, NULL),
  (d4, v_tour, 10, '10:00 PM', 'meeting',  'Meet at Main Entrance Esplanade',           NULL, 'Located between Disneyland and California Adventure. Take shuttle back to Toy Story at 10:15 PM.',                                                                     'Main Entrance Esplanade, Disneyland Resort, Anaheim, CA', NULL, NULL, NULL, NULL, NULL, NULL),
  (d4, v_tour, 11, '11:00 PM', 'hotel',    'Arrive at Hotel',                           NULL, 'Lights out 11:15 PM.',                                                                                                                                                 '101 E Katella Ave, Anaheim, CA 92802',     NULL, NULL, NULL, NULL, NULL, NULL);

  -- ─── Day 5 — Jun 18 (Thursday): Knott's Berry Farm Performance ────────────────
  INSERT INTO agenda_items (day_id, tour_id, sort_order, time, type, title, detail, public_note, address, travel_method, contact_name, driver_note, internal_note, meal_pay_type, stipend_amount) VALUES
  (d5, v_tour, 1, '8:00 AM',  'free',     'Wake Up & Get Ready',          NULL, NULL,                                                                                                                                                                                                NULL,                                    NULL, NULL, NULL, NULL, NULL, NULL),
  (d5, v_tour, 2, '8:30 AM',  'food',     'Breakfast - Hotel',            NULL, 'Please wear wristband to breakfast.',                                                                                                                                                               '101 E Katella Ave, Anaheim, CA 92802',  NULL, NULL, NULL, NULL, 'group', NULL),
  (d5, v_tour, 3, '8:55 AM',  'travel',   'Depart for Knotts Berry Farm', 'About 15 minutes.', NULL,                                                                                                                                                                               '8039 Beach Blvd, Buena Park, CA 90620', 'bus', NULL, NULL, NULL, NULL, NULL),
  (d5, v_tour, 4, '9:15 AM',  'activity', 'Arrive at Knotts Berry Farm',  NULL, 'All Day Entrees: one entree and side every 90 minutes. All Day Drinks: unlimited fountain refills every 15 minutes. No outside food unless special dietary needs or baby food. One unopened water bottle per person allowed. Park is completely cashless.', '8039 Beach Blvd, Buena Park, CA 90620', NULL, NULL, NULL, NULL, NULL, NULL),
  (d5, v_tour, 5, '11:00 AM', 'activity', 'Walk to Wagon Camp Stage',     NULL, 'Meet for performance at Wagon Camp Stage at the North Gate.',                                                                                                                                       'Wagon Camp Stage, Knotts Berry Farm, Buena Park, CA', NULL, NULL, NULL, NULL, NULL, NULL),
  (d5, v_tour, 6, '11:30 AM', 'activity', 'Performance at Wagon Camp',    NULL, NULL,                                                                                                                                                                                                'Wagon Camp Stage, Knotts Berry Farm, Buena Park, CA', NULL, NULL, NULL, NULL, NULL, NULL),
  (d5, v_tour, 7, '6:00 PM',  'free',     'Optional Return to Hotel',     NULL, 'Optional chaperone group return to hotel. Waterslides open until 8 PM. Pool open until 10 PM.',                                                                                                     '101 E Katella Ave, Anaheim, CA 92802',  NULL, NULL, NULL, NULL, NULL, NULL),
  (d5, v_tour, 8, '8:00 PM',  'hotel',    'Meet & Depart for Hotel',      NULL, 'Lights out 10:00 PM.',                                                                                                                                                                              '101 E Katella Ave, Anaheim, CA',        'bus', NULL, NULL, NULL, NULL, NULL);

  -- ─── Day 6 — Jun 19 (Friday): Universal Studios STARS Performance ─────────────
  INSERT INTO agenda_items (day_id, tour_id, sort_order, time, type, title, detail, public_note, address, travel_method, contact_name, driver_note, internal_note, meal_pay_type, stipend_amount) VALUES
  (d6, v_tour, 1,  '7:00 AM',  'free',     'Wake Up & Get Ready',                NULL, NULL,                                                                                                                                                       NULL,                                          NULL, NULL, NULL, NULL, NULL, NULL),
  (d6, v_tour, 2,  '7:30 AM',  'food',     'Breakfast - Hotel',                  NULL, 'Please wear wristband to breakfast.',                                                                                                                      '101 E Katella Ave, Anaheim, CA 92802',        NULL, NULL, NULL, NULL, 'group', NULL),
  (d6, v_tour, 3,  '7:50 AM',  'travel',   'Depart for Universal Studios',       'About 1 hour.', NULL,                                                                                                                                            '100 Universal City Plaza, Universal City, CA','bus', NULL, NULL, NULL, NULL, NULL),
  (d6, v_tour, 4,  '9:00 AM',  'activity', 'Arrive at Universal Studios',        NULL, 'Universal Studios MAP available at guest services. Prepare for performance at 5 Towers Stage.',                                                          '100 Universal City Plaza, Universal City, CA',NULL, NULL, NULL, NULL, NULL, NULL),
  (d6, v_tour, 5,  '9:15 AM',  'activity', 'Check In with Universal Host',       NULL, 'A Universal representative will meet your group at the taxi stand near the bus drop off area, prior to main park security. Stay outside security — do not go through metal detectors until escorted.', '5 Towers Stage, Universal Studios Hollywood, CA', NULL, NULL, NULL, NULL, NULL, NULL),
  (d6, v_tour, 6,  '10:00 AM', 'activity', 'STARS Performance - 5 Towers Stage', NULL, NULL,                                                                                                                                                       '5 Towers Stage, Universal Studios Hollywood, CA', NULL, NULL, NULL, NULL, NULL, NULL),
  (d6, v_tour, 7,  '12:00 PM', 'food',     'Lunch - Universal Studios',          NULL, 'Linda recommends Three Broomsticks. The Butterbeer is amazing!',                                                                                          'Universal Studios Hollywood, CA',             NULL, NULL, NULL, NULL, 'stipend', 25),
  (d6, v_tour, 8,  '6:30 PM',  'activity', 'Group Photo at Universal Globe',     NULL, 'Meet at Universal Globe sign for group photo.',                                                                                                            'Universal Globe, Universal Studios Hollywood, CA', NULL, NULL, NULL, NULL, NULL, NULL),
  (d6, v_tour, 9,  '6:45 PM',  'food',     'Dinner at City Walk',                NULL, 'Options: Panda Express, KFC, Taco Bell, Bubba Gump Shrimp, Firehouse Subs, Luigi''s Pizza and more.',                                                     'Universal CityWalk, Universal City, CA',      NULL, NULL, NULL, NULL, 'stipend', 25),
  (d6, v_tour, 10, '8:00 PM',  'travel',   'Load Bus & Depart for Hotel',        'About 1 hour.', NULL,                                                                                                                                            '101 E Katella Ave, Anaheim, CA 92802',        'bus', NULL, NULL, NULL, NULL, NULL),
  (d6, v_tour, 11, '9:00 PM',  'hotel',    'Arrive at Hotel',                    NULL, 'Please spend time packing your bag tonight. Lights out 10:00 PM.',                                                                                         '101 E Katella Ave, Anaheim, CA 92802',        NULL, NULL, NULL, NULL, NULL, NULL);

  -- ─── Day 7 — Jun 20 (Saturday): Return Anaheim → Idaho Falls ──────────────────
  INSERT INTO agenda_items (day_id, tour_id, sort_order, time, type, title, detail, public_note, address, travel_method, contact_name, driver_note, internal_note, meal_pay_type, stipend_amount) VALUES
  (d7, v_tour, 1,  '5:45 AM',  'free',    'Wake Up, Pack & Get Ready',          NULL, NULL,                                                                            NULL,                                       NULL, NULL, NULL, NULL, NULL, NULL),
  (d7, v_tour, 2,  '6:15 AM',  'food',    'Breakfast - Hotel',                  NULL, 'Please wear wristband to breakfast.',                                           '101 E Katella Ave, Anaheim, CA 92802',     NULL, NULL, NULL, NULL, 'group', NULL),
  (d7, v_tour, 3,  '7:00 AM',  'travel',  'Depart for Terrible''s - Jean, NV',  'About 3.5 to 4 hours.', NULL,                                                          '22625 NV-161, Jean, NV 89019',             'bus', NULL, NULL, NULL, NULL, NULL),
  (d7, v_tour, 4,  '11:00 AM', 'food',    'Lunch Stop - Terrible''s, Jean NV',  NULL, '40 minute stop. Grab food and eat on the bus.',                                 '22625 NV-161, Jean, NV 89019',             NULL, NULL, NULL, NULL, 'stipend', 15),
  (d7, v_tour, 5,  '11:40 AM', 'travel',  'Depart for Cedar City, Utah',        'About 3.5 hours. Time change entering Utah — lose one hour (1:15 PM becomes 2:15 PM).', NULL,                                          '1405 S Main St, Cedar City, UT 84720',     'bus', NULL, NULL, NULL, NULL, NULL),
  (d7, v_tour, 6,  '3:10 PM',  'free',    'Arrive Cedar City - Driver Swap & Break', NULL, '20 minute bathroom break.',                                                '1405 S Main St, Cedar City, UT 84720',     NULL, NULL, NULL, 'Boost Driver swap here.', NULL, NULL),
  (d7, v_tour, 7,  '3:30 PM',  'travel',  'Depart for Pizza Pie Cafe - Orem',   'About 3 to 3.5 hours.', NULL,                                                          '573 W 1600 N, Orem, UT 84057',             'bus', NULL, NULL, NULL, NULL, NULL),
  (d7, v_tour, 8,  '6:45 PM',  'food',    'Group Dinner - Pizza Pie Cafe',      NULL, 'Group meal — all paid.',                                                        '573 W 1600 N, Orem, UT 84057',             NULL, NULL, NULL, 'Group meal paid for 40 people with drinks. Phone: 801-226-4277.', 'group', NULL),
  (d7, v_tour, 9,  '7:45 PM',  'travel',  'Depart for Idaho Falls',             'About 3.5 hours.', NULL,                                                               '5366 1st St, Idaho Falls, ID 83401',       'bus', NULL, NULL, NULL, NULL, NULL),
  (d7, v_tour, 10, '9:45 PM',  'free',    'Rest Area Stop if Needed',           NULL, NULL,                                                                            'Rest area along I-15',                     NULL, NULL, NULL, NULL, NULL, NULL),
  (d7, v_tour, 11, '11:30 PM', 'meeting', 'Arrive Home - Idaho Falls',          NULL, 'Welcome home! Parents please be here by 11:15 PM.',                             '5366 1st St, Idaho Falls, ID 83401',       NULL, NULL, NULL, NULL, NULL, NULL);

  -- ─── Post-Trip placeholder ────────────────────────────────────────────────────
  INSERT INTO post_trip (tour_id, completed) VALUES (v_tour, false);

END $$;
